apiVersion: v1
kind: Pod
metadata:
  name: lab-pod
  labels:
    app: lab-pod
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Hi! I'm an environment variable of lab
    image: quay.io/practicalopenshift/hello-world
    imagePullPolicy: Always
    name: lab-pod-container
    resources: {}
